many fixes

diff --git a/baggage b/baggage
--- a/baggage
+++ b/baggage
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 trap "exit 1" TERM
-export TOP_PID=$$
+TOP_PID=$$
 
 Helpers()
 {
@@ -37,7 +37,7 @@ Baggage()
   new()
   {
     if [ -z "$BAGGAGE_CONF" ]; then
-      export BAGGAGE_CONF="$HOME/.baggage"
+      BAGGAGE_CONF="$HOME/.baggage"
     fi
 
     if [ -r "$BAGGAGE_CONF" ]; then
@@ -45,46 +45,45 @@ Baggage()
     fi
 
     if [ -z "$BAGGAGE_HOST" ]; then
-      export BAGGAGE_HOST="api.baggage.io"
+      BAGGAGE_HOST="api.baggage.io"
     fi
 
     if [ -z "$BAGGAGE_PROTO" ]; then
-      export BAGGAGE_PROTO="https"
+      BAGGAGE_PROTO="https"
     fi
 
     if [ -z "$BAGGAGE_PORT" ]; then
       if [ "$BAGGAGE_PROTO" = "http" ]; then
-        export BAGGAGE_PORT="80"
+        BAGGAGE_PORT="80"
       else
-        export BAGGAGE_PORT="443"
+        BAGGAGE_PORT="443"
       fi
     fi
 
     if [ -z "$BAGGAGE_CURL_OPTS" ]; then
-      export BAGGAGE_CURL_OPTS="-s"
+      BAGGAGE_CURL_OPTS=(-s -H 'Accept: text/plain')
     fi
 
     if [ -z "$BAGGAGE_WGET_OPTS" ]; then
-      export BAGGAGE_WGET_OPTS="-O - -q"
+      BAGGAGE_WGET_OPTS=(-O - -q --header='Accept: text/plain') 
     fi
 
     if [ -z "$BAGGAGE_HTTP_COMMAND" ]; then
-      export COMMAND=$(which curl)
+      COMMAND=$(which curl)
       if [ $? -eq 0 ]; then
-        export COMMAND_NAME="curl"
+        COMMAND_NAME="curl"
       else
-        export COMMAND=$(which wget)
-        if $? -eq 0 ]; then
-          export COMMAND_NAME="wget"
+        COMMAND=$(which wget)
+        if [ $? -eq 0 ]; then
+          COMMAND_NAME="wget"
         else
           Helpers;fatal "Please install curl or wget"
         fi
       fi
     else
-      export COMMAND="$BAGGAGE_HTTP_COMMAND"
-      export COMMAND_NAME="$BAGGAGE_HTTP_COMMAND_NAME"
+      COMMAND="$BAGGAGE_HTTP_COMMAND"
+      COMMAND_NAME="$BAGGAGE_HTTP_COMMAND_NAME"
     fi
-
   }
 
   id()
@@ -101,17 +100,29 @@ Baggage()
   {
     echo $BAGGAGE_ADMIN_TOKEN
   }
-  
+
   call()
   {
     URL="${BAGGAGE_PROTO}://${BAGGAGE_HOST}:${BAGGAGE_PORT}/${1}"
     if [ "$COMMAND_NAME" = "curl" ]; then
-      $COMMAND $BAGGAGE_CURL_OPTS -H 'Accept: text/plain' "$URL"
+      $COMMAND "${BAGGAGE_CURL_OPTS[@]}" "$URL"
     elif [ "$COMMAND_NAME" = "wget" ]; then
-      $COMMAND $BAGGAGE_WGET_OPTS --header='Accept: text/plain' "$URL"
+      $COMMAND $BAGGAGE_WGET_OPTS "${BAGGAGE_WGET_OPTS[@]}" "$URL"
     else
-      $COMMAND $BAGGAGE_HTTP_COMMAND_OPTS "$URL"
+      $COMMAND "${BAGGAGE_HTTP_COMMAND_OPTS[@]}" "$URL"
     fi
+  }
+
+  call_post()
+  {
+    url="$1"
+    BAGGAGE_CURL_OPTS=(-XPOST --data-binary @- "${BAGGAGE_CURL_OPTS[@]}" -H 'Content-Type: application/octet-stream')
+
+    if [ "$COMMAND_NAME" = "wget" ]; then
+      Helpers;fatal "Sorry, you cannot currently POST using wget. Please install curl or use the body parameter"
+    fi
+
+    cat | call "$url"
   }
 
   subscribe()
@@ -153,14 +164,16 @@ Baggage()
       shift
     done
 
-    call_command="send/$(id)?token=$(email_token)&subject=${subject}"
+    call_url="send/$(id)?token=$(email_token)&subject=${subject}"
 
     if [ -n "$from" ]; then
-      call_command="${call_command}&from=${from}"
+      call_url="${call_command}&from=${from}"
     fi
 
     if [ -n "$body" ]; then
-      call "${call_command}&body=${body}"
+      call "${call_url}&body=${body}"
+    else
+      cat | call_post "$call_url"
     fi
   }
 
@@ -177,42 +190,44 @@ Baggage()
     fi
 
     cat <<EOF
-usage: baggage COMMAND [OPTS]
+
+Usage: baggage COMMAND [OPTS]
 
 Commands:
 
     subscribe EMAIL
 
-      Subscribes email address.
+        Subscribes email address.
 
     stats
 
-      Retrieves stats for subscription.
+       Retrieves stats for subscription.
 
     rotate
 
-      Rotates tokens.
+       Rotates tokens.
 
     unsubscribe
 
-      Unsubscribes.
+       Unsubscribes.
 
     send SUBJECT [OPTS] [BODY]
 
-      Sends email. Options are:
+       Sends email. Options are:
 
-      -f --from       Email from name
-      -b --body       Email body. If not provided, body is read from STDIN.
+       -f --from       Email from name.
+       -b --body       Email body. If not provided, body is read from STDIN.
 
     ping
 
-      Basic connectivity test.
+       Basic connectivity test.
 
     help
 
-      This help.
+       This help.
 
-      See https://github.com/baggage/app for full API docs
+       See https://github.com/baggage/app for full API docs
+
 EOF
   }
 }
@@ -229,5 +244,5 @@ case "$command" in
   'send') Baggage;send "$@";;
   'ping') Baggage;ping "$@";;
   'help') Baggage;usage;;
-  *) Baggage;usage "unknown command";;
+  *) Baggage;usage "unknown command $command";;
 esac
